Homework 4
AntonBelia/homework1 pull request #5
Opened 2023-07-03 12:51 UTC by AntonBelia

2023-07-04 11:06 UTC, myroslav-kolomiiets requested changes
Хороший початок, але є що переробити. Залишив відео ревью: https://vimeo.com/842150652/e5ce0c15da

2023-07-06 21:39 UTC, myroslav-kolomiiets requested changes
На цей момент, після перезавантаження сторінки, на залишається вибрана тема.

2023-07-06 21:39 UTC, myroslav-kolomiiets commented on js/homework_4.js
> +if (!bgColorTheme || !lastToggleTime) {
Задавати значення, якщо їх не має в локал сторедж, не має сенсу, краще на рядку 11 та 12 записувати в змінні або з локал сторадж, або, якщо їх там ще не має, класти в змінні якісь дефолтні значення.

2023-07-06 21:39 UTC, myroslav-kolomiiets commented on js/homework_4.js
> +if (bgColorTheme === "light") {
Можна об'єднати з рядком 36

2023-07-06 21:39 UTC, myroslav-kolomiiets commented on js/homework_4.js
> +      document.body.classList.add("dark");
всю логіку з contains, remove та add, можна замінити на toggle (і правильно замінити на toggle)

2023-07-07 08:58 UTC, AntonBelia commented on js/homework_4.js
> +if (!bgColorTheme || !lastToggleTime) {
добавив значення коли оголошую змінну.

2023-07-07 08:58 UTC, AntonBelia commented on js/homework_4.js
> +if (bgColorTheme === "light") {
обєднав

2023-07-07 08:59 UTC, AntonBelia commented on js/homework_4.js
> +      document.body.classList.add("dark");
замінив логіку на додавання теми через тоггл

2023-07-07 09:01 UTC, AntonBelia commented on js/homework_4.js
> +      document.body.classList.add("dark");
Довго не міг зрозуміти чому не коректно працює після перезавантаження сторінки, виявилось що в html в боді я відразу вказав класс світлої теми, і додавались 2 теми відразую

2023-07-07 15:02 UTC, myroslav-kolomiiets requested changes
Можна ще більш спростити рішення.
Зараз тоглиться дві теми, можна залишити тільки dark, а стилі світлої прописати як дефолтні.

2023-07-10 11:23 UTC, myroslav-kolomiiets approved these changes

2023-07-10 11:40 UTC, merged