Iterator and generator
AntonBelia/homework1 pull request #9
Opened 2023-08-18 08:45 UTC by AntonBelia

2023-08-22 13:38 UTC, myroslav-kolomiiets requested changes

2023-08-22 13:38 UTC, myroslav-kolomiiets commented on js/iteratorAndGenerator.js
> +// fizzBuzz[Symbol.iterator] = function* () {
Треба було вирішити задачу двома способами, через ітератор і через генератор. У вас два в одному) Треба переробити

2023-08-22 13:38 UTC, myroslav-kolomiiets commented on js/iteratorAndGenerator.js
> +function* generateRandomNumbers(max, quantity) {
Тут вірно

2023-08-22 13:38 UTC, myroslav-kolomiiets commented on js/iteratorAndGenerator.js
> +for (value of randomNumber) {
```suggestion
for (let value of randomNumber) {
```

Не забувайте про змінні та strict mode

2023-08-22 19:42 UTC, AntonBelia commented on js/iteratorAndGenerator.js
> +// fizzBuzz[Symbol.iterator] = function* () {
не уважно прочитав умову задачі.

2023-08-24 13:56 UTC, myroslav-kolomiiets approved these changes
Все вірно, апрув

2023-08-24 14:53 UTC, merged